name: PumpkinLamp
main: com.aaaaahhhhhhh.bananapuncher714.pumpkinlamp.PumpkinLamp
version: 1.0.2
description: Add redstone toggleable pumpkin lamps
author: BananaPuncher714
api-version: 1.13
load: STARTUP
depend:
- DimensionalBlocks